language: php
php:
  - '7.2'
cache:
  - laravel/vendor
before_script:
  - cd ./laravel 
  - composer install
script:
  - pwd
  - cp example.env .env
  - php artisan key:generate
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit