version: "3"
services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./laravel:/var/www/html/laravel
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./laravel:/var/www/html/laravel